---

- name: "recv message, room={{ room }} zx={{ zx }}"
  shell: "PATH=/home/ubuntu/.nvm/versions/node/v8.9.4/bin/ DEBUG=app:*,signal:* benchmark-leancloud --role recv --env prod --room {{ room }} --zx {{ zx }} >>/home/ubuntu/recv.log 2>&1 &"
  tags: cron_recv_add
  async: 3600
  poll: 2

- name: "remove recv message, room={{ room }} zx={{ zx }}"
  shell: "ps aux | grep 'role recv' | head -n 1 | awk '{print $2}' | xargs kill -9"
  tags: cron_recv_remove



