---

- name: install "aoc-signal-cli" npm package
  tags: npm
  npm:
    name: aoc-signal-cli
    global: yes
    state: latest
    #executable: "/home/ubuntu/.nvm/versions/node/{{node_version}}/bin/npm"
  environment:
    PATH: "/home/ubuntu/.nvm/versions/node/{{node_version}}/bin:{{ ansible_env.PATH }}"
