---

- hosts: aws-test aws-us aws-sgp
  remote_user: "{{ aws_user }}"
  roles:
  - role: leonidas.nvm
    become: true
    become_method: sudo
    tags: nvm
    nvm:
      user: "{{ aws_user }}"
      version: v0.33.0
      node_version: "{{ node_version }}"
      executable: "~/.nvm/versions/node/{{ node_version }}/bin/npm"
  - install
#  - cron



